import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";

import { ThemeProvider } from "./../context/ThemeContext";

const bodyFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata = {
  title: "Solar Survey App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <ThemeProvider>
          <div className="container">
            <Header />

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
